### ISSUE TITLE
Run 2.0.16 Upgrade Test Work Out Failures

### ISSUE THREAD

**Issue by stjaxn** [woopignet/woopig-board#49]

**Comment by stjaxn** [comment]
If you're also going to work on the conflicts, we need to decide who's doing what so we don't both do the same thing. And don't push anything related to this up to the server unless you get a clean successful install on your local machine at home. @One-Quarter

**Comment by One-Quarter** [comment]
That’s a very good point.  I don’t even have a working install of the current software on my local machine.

**Comment by stjaxn** [comment]
In fact, you take the Dark Theme, I'll take all of the SMF upgrade stuff.

**Comment by stjaxn** [comment]
I'm almost done manually checking the conflicts. In every case, the action that needs to happen has already happened. The upgrade script finds a string and replaces it with another string. The reason it can't find the string is that it's already changed. I'm anticipating that I can run this and just ignore all errors. We'll see.

**Comment by stjaxn** [comment]
Doing this in the sandbox environment. I'm actually going to try to skip the upgrades. SMF has a 'Large Upgrade' package that can be used to upgrade several versions at a time. It's going to reset everything to a clean install and up to date. Then we can work on making it look right and adding in features.

I've got the files up there and taken care of everything except running the upgrade package. I plan on having that done Friday night or Saturday night. We can see how hard it's going to be to get the Woopig5 theme to work. We might throw up a lite version of it that doesn't have any bells or whistles so we can just get the fuck off that trashed up mess we're running now.  

In fact, that's the plan. I'm going to make a sandbox copy of the database from the current database. I'll point the sandbox environment at it and go through the upgrade process. If it goes off without a hitch, I'll throw together a theme that is basically just colored right and save it off somewhere. 

Then we'll announce an outage and take the board down and go through the upgrade process in the Sandbox again and if successful, I'll copy all that code to the /board directory and then bring the board back up. I'll put that theme in place and force everyone on it.

Then we just work on gussying the joint up. On a clean up to date version of everything.

 @One-Quarter

**Comment by One-Quarter** [comment]
Do it.  I’m fully on-board.  We can fix up the features after SMF is stable.

**Comment by stjaxn** [comment]
Closing this as using the large update makes this a non-issue.
